// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	App: {
		/**
		 * A​ ​c​a​r​r​e​g​a​r
		 */
		Loading: string
		/**
		 * S​e​m​ ​L​o​g​i​n
		 */
		NoLogin: string
		/**
		 * O​ ​u​t​i​l​i​z​a​d​o​r​ ​n​e​c​e​s​s​i​t​a​ ​d​e​ ​f​a​z​e​r​ ​o​ ​l​o​g​i​n​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​a​ ​p​á​g​i​n​a​.
		 */
		NoLoginDesc: string
		/**
		 * U​t​i​l​i​z​a​d​o​r​ ​n​ã​o​ ​t​e​m​ ​t​i​p​o​ ​d​e​ ​p​e​r​f​i​l
		 */
		NoUserProfileType: string
		/**
		 * O​ ​u​t​i​l​i​z​a​d​o​r​ ​n​ã​o​ ​t​e​m​ ​n​e​n​h​u​m​ ​t​i​p​o​ ​d​e​ ​p​e​r​f​i​l​ ​a​s​s​o​c​i​a​d​o​ ​s​e​j​a​ ​f​r​o​n​t​o​f​f​i​c​e​ ​o​u​ ​b​a​c​k​o​f​f​i​c​e​.​ ​T​e​n​t​e​ ​s​o​l​u​c​i​o​n​a​r​ ​e​s​t​e​ ​p​r​o​b​l​e​m​a​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​a​ ​p​á​g​i​n​a​.
		 */
		NoUserProfileTypeDesc: string
	}
	Header: {
		/**
		 * I​n​í​c​i​o
		 */
		Home: string
	}
	HomeBackoffice: {
		/**
		 * A​v​a​l​i​a​ç​õ​e​s​ ​A​t​i​v​a​s
		 */
		ActiveReviews: string
		/**
		 * A​v​a​l​i​a​ç​õ​e​s​ ​C​o​m​p​l​e​t​a​s
		 */
		CompletedReviews: string
		/**
		 * A​v​a​l​i​a​ç​õ​e​s
		 */
		Reviews: string
		/**
		 * M​o​d​e​l​o​s
		 */
		Templates: string
	}
	Menu: {
		/**
		 * I​n​í​c​i​o
		 */
		Home: string
		/**
		 * D​e​s​e​m​p​e​n​h​o
		 */
		Performance: string
		/**
		 * P​e​r​m​i​s​s​õ​e​s
		 */
		Permissions: string
		/**
		 * A​v​a​l​i​a​ç​õ​e​s
		 */
		Reviews: string
		/**
		 * E​s​t​a​t​í​s​t​i​c​a​s
		 */
		Statistics: string
		/**
		 * S​u​b​m​i​s​s​õ​e​s
		 */
		Submissions: string
		/**
		 * D​e​s​e​m​p​e​n​h​o​ ​E​q​u​i​p​a
		 */
		TeamPerformance: string
		/**
		 * M​o​d​e​l​o​s
		 */
		Templates: string
	}
	Permissions: {
		/**
		 * S​e​l​e​c​i​o​n​a​r​ ​p​e​r​f​i​l
		 */
		ChooseProfile: string
		/**
		 * S​e​l​e​c​i​o​n​e​ ​o​ ​p​e​r​f​i​l​ ​a​o​ ​q​u​a​l​ ​d​e​s​e​j​a​ ​a​l​t​e​r​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s
		 */
		ChooseProfileDesc: string
		/**
		 * A​ ​c​a​r​r​e​g​a​r
		 */
		Loading: string
		PermissionType: {
			/**
			 * C​r​i​a​r
			 */
			Create: string
			/**
			 * R​e​m​o​v​e​r
			 */
			Delete: string
			/**
			 * A​l​t​e​r​a​r​ ​e​s​t​a​d​o
			 */
			Patch: string
			/**
			 * A​c​e​s​s​a​r
			 */
			Read: string
			/**
			 * E​d​i​t​a​r
			 */
			Update: string
		}
		/**
		 * P​e​r​m​i​s​s​õ​e​s​ ​d​o​ ​p​e​r​f​i​l​ ​g​u​a​r​d​a​d​a​s​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		PermissionsSave: string
		/**
		 * O​c​o​r​r​e​u​ ​u​m​ ​e​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​g​r​a​v​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​d​o​ ​p​e​r​f​i​l
		 */
		PermissionsSaveError: string
		/**
		 * G​u​a​r​d​a​r
		 */
		Save: string
	}
	Sidebar: {
		/**
		 * M​e​n​u​ ​B​a​c​k​o​f​f​i​c​e
		 */
		Backoffice: string
		/**
		 * M​e​n​u​ ​F​r​o​n​t​o​f​f​i​c​e
		 */
		Frontoffice: string
		/**
		 * O​l​á
		 */
		Hello: string
		/**
		 * U​t​i​l​i​z​a​d​o​r
		 */
		User: string
	}
	Templates: {
		/**
		 * C​r​i​a​r​ ​m​o​d​e​l​o
		 */
		CreateTemplate: string
		/**
		 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​l​i​s​t​a​r​ ​o​s​ ​m​o​d​e​l​o​s
		 */
		Error: string
		/**
		 * F​i​l​t​r​a​r​ ​m​o​d​e​l​o​s​ ​p​e​l​o​ ​t​í​t​u​l​o​.​.​.
		 */
		InputText: string
		/**
		 * N​ã​o​ ​e​x​i​s​t​e​m​ ​m​o​d​e​l​o​s​ ​d​i​s​p​o​n​í​v​e​i​s​ ​d​e​ ​m​o​m​e​n​t​o​.​ ​V​o​l​t​e​ ​m​a​i​s​ ​t​a​r​d​e​ ​o​u​ ​c​r​i​e​ ​u​m​ ​n​o​v​o​ ​m​o​d​e​l​o​ ​p​a​r​a​ ​c​o​m​e​ç​a​r​!
		 */
		NoTemplates: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​n​t​r​a​d​o​s​ ​m​o​d​e​l​o​s​ ​q​u​e​ ​c​o​r​r​e​s​p​o​n​d​a​m​ ​à​ ​s​u​a​ ​p​e​s​q​u​i​s​a​.​ ​T​e​n​t​e​ ​a​j​u​s​t​a​r​ ​a​s​ ​p​a​l​a​v​r​a​s​-​c​h​a​v​e​ ​o​u​ ​l​i​m​p​e​ ​o​ ​f​i​l​t​r​o​ ​p​a​r​a​ ​v​e​r​ ​t​o​d​o​s​ ​o​s​ ​m​o​d​e​l​o​s​ ​d​i​s​p​o​n​í​v​e​i​s​.
		 */
		NoTemplatesFilter: string
		/**
		 * P​r​é​ ​V​i​s​u​a​l​i​z​a​r
		 */
		Preview: string
		/**
		 * E​x​i​b​i​n​d​o​ ​{​f​i​r​s​t​E​l​e​m​e​n​t​}​ ​a​t​é​ ​{​p​a​g​e​S​i​z​e​}​ ​d​e​ ​{​t​o​t​a​l​}​ ​i​t​e​m​s
		 * @param {unknown} firstElement
		 * @param {unknown} pageSize
		 * @param {unknown} total
		 */
		ShowingItemsLabel: RequiredParams<'firstElement' | 'pageSize' | 'total'>
		/**
		 * M​o​d​e​l​o​s
		 */
		Templates: string
		/**
		 * M​o​d​e​l​o​ ​r​e​m​o​v​i​d​o​ ​c​o​m​ ​s​u​c​c​e​s​s​o​.
		 */
		ToastDelete: string
		/**
		 * E​r​r​o​ ​a​o​ ​r​e​m​o​v​e​r​ ​m​o​d​e​l​o​.​ ​T​e​n​t​e​ ​d​e​ ​n​o​v​o​.
		 */
		ToastErrorDelete: string
	}
}

export type TranslationFunctions = {
	App: {
		/**
		 * A carregar
		 */
		Loading: () => LocalizedString
		/**
		 * Sem Login
		 */
		NoLogin: () => LocalizedString
		/**
		 * O utilizador necessita de fazer o login antes de acessar a página.
		 */
		NoLoginDesc: () => LocalizedString
		/**
		 * Utilizador não tem tipo de perfil
		 */
		NoUserProfileType: () => LocalizedString
		/**
		 * O utilizador não tem nenhum tipo de perfil associado seja frontoffice ou backoffice. Tente solucionar este problema antes de acessar a página.
		 */
		NoUserProfileTypeDesc: () => LocalizedString
	}
	Header: {
		/**
		 * Início
		 */
		Home: () => LocalizedString
	}
	HomeBackoffice: {
		/**
		 * Avaliações Ativas
		 */
		ActiveReviews: () => LocalizedString
		/**
		 * Avaliações Completas
		 */
		CompletedReviews: () => LocalizedString
		/**
		 * Avaliações
		 */
		Reviews: () => LocalizedString
		/**
		 * Modelos
		 */
		Templates: () => LocalizedString
	}
	Menu: {
		/**
		 * Início
		 */
		Home: () => LocalizedString
		/**
		 * Desempenho
		 */
		Performance: () => LocalizedString
		/**
		 * Permissões
		 */
		Permissions: () => LocalizedString
		/**
		 * Avaliações
		 */
		Reviews: () => LocalizedString
		/**
		 * Estatísticas
		 */
		Statistics: () => LocalizedString
		/**
		 * Submissões
		 */
		Submissions: () => LocalizedString
		/**
		 * Desempenho Equipa
		 */
		TeamPerformance: () => LocalizedString
		/**
		 * Modelos
		 */
		Templates: () => LocalizedString
	}
	Permissions: {
		/**
		 * Selecionar perfil
		 */
		ChooseProfile: () => LocalizedString
		/**
		 * Selecione o perfil ao qual deseja alterar as permissões
		 */
		ChooseProfileDesc: () => LocalizedString
		/**
		 * A carregar
		 */
		Loading: () => LocalizedString
		PermissionType: {
			/**
			 * Criar
			 */
			Create: () => LocalizedString
			/**
			 * Remover
			 */
			Delete: () => LocalizedString
			/**
			 * Alterar estado
			 */
			Patch: () => LocalizedString
			/**
			 * Acessar
			 */
			Read: () => LocalizedString
			/**
			 * Editar
			 */
			Update: () => LocalizedString
		}
		/**
		 * Permissões do perfil guardadas com sucesso
		 */
		PermissionsSave: () => LocalizedString
		/**
		 * Ocorreu um erro ao tentar gravar as permissões do perfil
		 */
		PermissionsSaveError: () => LocalizedString
		/**
		 * Guardar
		 */
		Save: () => LocalizedString
	}
	Sidebar: {
		/**
		 * Menu Backoffice
		 */
		Backoffice: () => LocalizedString
		/**
		 * Menu Frontoffice
		 */
		Frontoffice: () => LocalizedString
		/**
		 * Olá
		 */
		Hello: () => LocalizedString
		/**
		 * Utilizador
		 */
		User: () => LocalizedString
	}
	Templates: {
		/**
		 * Criar modelo
		 */
		CreateTemplate: () => LocalizedString
		/**
		 * Erro ao tentar listar os modelos
		 */
		Error: () => LocalizedString
		/**
		 * Filtrar modelos pelo título...
		 */
		InputText: () => LocalizedString
		/**
		 * Não existem modelos disponíveis de momento. Volte mais tarde ou crie um novo modelo para começar!
		 */
		NoTemplates: () => LocalizedString
		/**
		 * Não foram encontrados modelos que correspondam à sua pesquisa. Tente ajustar as palavras-chave ou limpe o filtro para ver todos os modelos disponíveis.
		 */
		NoTemplatesFilter: () => LocalizedString
		/**
		 * Pré Visualizar
		 */
		Preview: () => LocalizedString
		/**
		 * Exibindo {firstElement} até {pageSize} de {total} items
		 */
		ShowingItemsLabel: (arg: { firstElement: unknown, pageSize: unknown, total: unknown }) => LocalizedString
		/**
		 * Modelos
		 */
		Templates: () => LocalizedString
		/**
		 * Modelo removido com successo.
		 */
		ToastDelete: () => LocalizedString
		/**
		 * Erro ao remover modelo. Tente de novo.
		 */
		ToastErrorDelete: () => LocalizedString
	}
}

export type Formatters = {}
