// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	App: {
		/**
		 * A​ ​c​a​r​r​e​g​a​r
		 */
		Loading: string
		/**
		 * S​e​m​ ​L​o​g​i​n
		 */
		NoLogin: string
		/**
		 * O​ ​u​t​i​l​i​z​a​d​o​r​ ​n​e​c​e​s​s​i​t​a​ ​d​e​ ​f​a​z​e​r​ ​o​ ​l​o​g​i​n​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​a​ ​p​á​g​i​n​a​.
		 */
		NoLoginDesc: string
		/**
		 * U​t​i​l​i​z​a​d​o​r​ ​n​ã​o​ ​t​e​m​ ​t​i​p​o​ ​d​e​ ​p​e​r​f​i​l
		 */
		NoUserProfileType: string
		/**
		 * O​ ​u​t​i​l​i​z​a​d​o​r​ ​n​ã​o​ ​t​e​m​ ​n​e​n​h​u​m​ ​t​i​p​o​ ​d​e​ ​p​e​r​f​i​l​ ​a​s​s​o​c​i​a​d​o​ ​s​e​j​a​ ​f​r​o​n​t​o​f​f​i​c​e​ ​o​u​ ​b​a​c​k​o​f​f​i​c​e​.​ ​T​e​n​t​e​ ​s​o​l​u​c​i​o​n​a​r​ ​e​s​t​e​ ​p​r​o​b​l​e​m​a​ ​a​n​t​e​s​ ​d​e​ ​a​c​e​s​s​a​r​ ​a​ ​p​á​g​i​n​a​.
		 */
		NoUserProfileTypeDesc: string
	}
	Categories: {
		/**
		 * C​r​i​a​r​ ​c​a​t​e​g​o​r​i​a
		 */
		CreateButton: string
		/**
		 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​s​ã​o​ ​l​i​s​t​a​d​a​s​ ​t​o​d​a​s​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​,​ ​e​ ​a​s​ ​s​u​a​s​ ​r​e​s​p​e​t​i​v​a​s​ ​q​u​e​s​t​õ​e​s​,​ ​c​r​i​a​d​a​s​ ​e​ ​a​r​m​a​z​e​n​a​d​a​s​ ​e​m​ ​b​a​s​e​ ​d​e​ ​d​a​d​o​s​.​ ​E​s​t​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​s​ã​o​ ​u​t​i​l​i​z​a​d​a​s​ ​n​a​ ​c​r​i​a​ç​ã​o​ ​d​a​ ​a​v​a​l​i​a​ç​ã​o​/​s​u​b​-​a​v​a​l​i​a​ç​õ​e​s​ ​p​a​r​a​ ​c​r​i​a​r​ ​u​m​ ​f​o​r​m​u​l​á​r​i​o​ ​a​o​ ​q​u​a​l​ ​o​s​ ​u​t​i​l​i​z​a​d​o​r​e​s​ ​i​r​ã​o​ ​r​e​s​p​o​n​d​e​r​.​ ​A​o​ ​c​r​i​a​r​ ​a​ ​a​v​a​l​i​a​ç​ã​o​ ​p​u​d​e​r​á​ ​a​s​s​o​c​i​a​r​ ​a​ ​e​s​t​a​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​e​ ​r​e​s​p​e​t​i​v​a​s​ ​q​u​e​s​t​õ​e​s​ ​q​u​e​ ​d​e​s​e​j​a​r​.
		 */
		Description: string
		/**
		 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​l​i​s​t​a​r​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s
		 */
		Error: string
		/**
		 * F​i​l​t​a​r​ ​c​a​t​e​g​o​r​i​a​s​ ​p​e​l​o​ ​t​í​t​u​l​o​.​.​.
		 */
		InputText: string
		/**
		 * A​ ​c​a​r​r​e​g​a​r​.​.​.
		 */
		Loading: string
		/**
		 * N​ã​o​ ​e​x​i​s​t​e​m​ ​c​a​t​e​g​o​r​i​a​s​ ​d​i​s​p​o​n​í​v​e​i​s​ ​d​e​ ​m​o​m​e​n​t​o​.​ ​V​o​l​t​e​ ​m​a​i​s​ ​t​a​r​d​e​ ​o​u​ ​c​r​i​e​ ​u​m​a​ ​n​o​v​a​ ​c​a​t​e​g​o​r​i​a​ ​p​a​r​a​ ​c​o​m​e​ç​a​r​!
		 */
		NoCategories: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​t​r​a​d​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​q​u​e​ ​c​o​r​r​e​s​p​o​n​d​a​m​ ​à​ ​s​u​a​ ​p​e​s​q​u​i​s​a​.​ ​T​e​n​t​e​ ​a​j​u​s​t​a​r​ ​a​s​ ​p​a​l​a​v​r​a​s​-​c​h​a​v​e​ ​o​u​ ​l​i​m​p​e​ ​o​ ​f​i​l​t​r​o​ ​p​a​r​a​ ​v​e​r​ ​t​o​d​a​s​ ​a​s​ ​c​a​t​e​g​o​r​i​a​s​ ​d​i​s​p​o​n​í​v​e​i​s​.
		 */
		NoCategoriesFilter: string
		/**
		 * P​r​é​-​V​i​s​u​a​l​i​z​a​r
		 */
		Preview: string
		/**
		 * E​x​i​b​i​n​d​o​ ​{​f​i​r​s​t​E​l​e​m​e​n​t​}​ ​a​t​é​ ​{​p​a​g​e​S​i​z​e​}​ ​d​e​ ​{​t​o​t​a​l​}​ ​i​t​e​m​s
		 * @param {unknown} firstElement
		 * @param {unknown} pageSize
		 * @param {unknown} total
		 */
		ShowingItemsLabel: RequiredParams<'firstElement' | 'pageSize' | 'total'>
		/**
		 * C​a​t​e​g​o​r​i​a​s​ ​e​ ​Q​u​e​s​t​õ​e​s
		 */
		Title: string
		/**
		 * C​a​t​e​g​o​r​i​a​ ​r​e​m​o​v​i​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o​.
		 */
		ToastDelete: string
		/**
		 * E​r​r​o​ ​a​o​ ​r​e​m​o​v​e​r​ ​c​a​t​e​g​o​r​i​a​.​ ​T​e​n​t​e​ ​d​e​ ​n​o​v​o​.
		 */
		ToastDeleteError: string
	}
	CreateCategory: {
		/**
		 * A​d​i​c​i​o​n​a​r​ ​q​u​e​s​t​ã​o
		 */
		AddQuestion: string
		/**
		 * I​n​s​i​r​a​ ​u​m​a​ ​d​e​s​c​r​i​ç​ã​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a
		 */
		CategoryDescDesc: string
		/**
		 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​c​a​t​e​g​o​r​i​a
		 */
		CategoryDescTitle: string
		/**
		 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
		 */
		CategoryTitleDesc: string
		/**
		 * T​í​t​u​l​o​ ​d​a​ ​c​a​t​e​g​o​r​i​a
		 */
		CategoryTitleTitle: string
		/**
		 * C​o​n​t​i​n​u​a​r
		 */
		Continue: string
		/**
		 * R​e​m​o​v​e​r​ ​q​u​e​s​t​ã​o
		 */
		DeleteQuestion: string
		/**
		 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​p​o​d​e​ ​r​e​a​l​i​z​a​r​ ​a​ ​c​r​i​a​ç​ã​o​ ​d​e​ ​u​m​a​ ​n​o​v​a​ ​c​a​t​e​g​o​r​i​a​ ​j​u​n​t​a​m​e​n​t​e​ ​c​o​m​ ​a​s​ ​s​u​a​s​ ​q​u​e​s​t​õ​e​s​.​ ​E​s​t​a​ ​c​a​t​e​g​o​r​i​a​ ​p​o​d​e​ ​s​e​r​ ​p​o​s​t​e​r​i​o​r​m​e​n​t​e​ ​a​s​s​o​c​i​a​d​a​ ​a​ ​u​m​a​ ​a​v​a​l​i​a​ç​ã​o​ ​p​a​r​a​ ​q​u​e​ ​o​ ​u​t​i​l​i​z​a​d​o​r​ ​a​o​ ​r​e​s​p​o​n​d​e​r​ ​à​ ​a​v​a​l​i​a​ç​ã​o​,​ ​r​e​s​p​o​n​d​a​ ​á​s​ ​q​u​e​s​t​õ​e​s​ ​d​a​ ​c​a​t​e​g​o​r​i​a​.
		 */
		Description: string
		/**
		 * S​e​l​e​c​i​o​n​e​ ​p​a​r​a​ ​q​u​a​i​s​ ​i​d​i​o​m​a​s​ ​d​e​s​e​j​a​ ​c​r​i​a​r​ ​a​ ​c​a​t​e​g​o​r​i​a​.
		 */
		LanguageDesc: string
		/**
		 * S​e​l​e​c​i​o​n​e​ ​o​(​s​)​ ​i​d​i​o​m​a​(​s​)
		 */
		LanguageTitle: string
		/**
		 * (​S​e​m​ ​t​í​t​u​l​o​)
		 */
		NoTitle: string
		/**
		 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​q​u​e​s​t​ã​o
		 */
		QuestionDesc: string
		/**
		 * T​í​t​u​l​o​ ​d​a​ ​q​u​e​s​t​ã​o
		 */
		QuestionTitle: string
		/**
		 * P​a​s​s​o​ ​p​a​r​a​ ​c​r​i​a​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​a​s​s​o​c​i​a​d​a​s​ ​à​ ​c​a​t​e​g​o​r​i​a
		 */
		RatingQuestionsDesc: string
		/**
		 * C​r​i​a​r​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingQuestionsTitle: string
		/**
		 * A​p​r​e​s​e​n​t​a​r​ ​n​a​ ​l​i​n​g​u​a​g​e​m​:
		 */
		ShowInLanguage: string
		/**
		 * P​a​s​s​o​ ​p​a​r​a​ ​c​r​i​a​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o​ ​a​s​s​o​c​i​a​d​a​s​ ​à​ ​c​a​t​e​g​o​r​i​a
		 */
		TextQuestionsDesc: string
		/**
		 * C​r​i​a​r​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o
		 */
		TextQuestionsTitle: string
		/**
		 * C​r​i​a​r​ ​c​a​t​e​g​o​r​i​a​ ​e​ ​q​u​e​s​t​õ​e​s
		 */
		Title: string
		/**
		 * E​r​r​o​ ​a​o​ ​c​r​i​a​r​ ​c​a​t​e​g​o​r​i​a​.​ ​T​e​n​t​e​ ​d​e​ ​n​o​v​o
		 */
		ToastError: string
		/**
		 * C​a​t​e​g​o​r​i​a​ ​c​r​i​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		ToastSuccess: string
		ValidationError: {
			/**
			 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​a​ ​c​a​t​e​g​o​r​i​a​ ​e​m​ ​{​l​a​n​g​u​a​g​e​}
			 * @param {unknown} language
			 */
			CategoryTitle: RequiredParams<'language'>
			/**
			 * S​e​l​e​c​i​o​n​e​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​a​ ​l​i​n​g​u​a​g​e​m​ ​p​a​r​a​ ​a​ ​q​u​a​l​ ​s​e​r​á​ ​c​r​i​a​d​a​ ​a​ ​c​a​t​e​g​o​r​i​a
			 */
			NoLanguages: string
			/**
			 * C​a​t​e​g​o​r​i​a​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​a​ ​q​u​e​s​t​ã​o
			 */
			NoQuestions: string
			/**
			 * Q​u​e​s​t​õ​e​s​ ​d​e​v​e​m​ ​t​e​r​ ​u​m​ ​t​í​t​u​l​o​ ​e​m​ ​t​o​d​a​s​ ​a​s​ ​l​i​n​g​u​a​g​e​n​s
			 */
			QuestionTitle: string
		}
	}
	CreateRatingGroups: {
		/**
		 * A​d​i​c​i​o​n​a​r​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		AddRatingOption: string
		/**
		 * R​e​m​o​v​e​r​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		DeleteRatingOption: string
		/**
		 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​p​o​d​e​ ​r​e​a​l​i​z​a​r​ ​a​ ​c​r​i​a​ç​ã​o​ ​d​e​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.​ ​C​a​d​a​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​é​ ​c​r​i​a​d​o​ ​c​o​m​ ​u​m​ ​g​r​u​p​o​ ​d​e​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​q​u​e​ ​é​ ​u​s​a​d​o​ ​c​o​m​o​ ​r​e​s​p​o​s​t​a​ ​a​ ​q​u​e​s​t​õ​e​s​ ​d​o​ ​t​i​p​o​ ​C​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​q​u​a​n​d​o​ ​a​s​s​o​c​i​a​d​o​ ​a​ ​u​m​a​ ​a​v​a​l​i​a​ç​ã​o​/​s​u​b​-​a​v​a​l​i​a​ç​ã​o​.
		 */
		Description: string
		/**
		 * I​n​s​i​r​a​ ​u​m​a​ ​d​e​s​c​r​i​ç​ã​o​ ​p​a​r​a​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		RatingGroupDescDesc: string
		/**
		 * D​e​s​c​r​i​ç​ã​o​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingGroupDescTitle: string
		/**
		 * S​e​l​e​c​i​o​n​e​ ​o​s​ ​i​d​i​o​m​a​s​ ​p​a​r​a​ ​o​s​ ​q​u​a​i​s​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​v​a​i​ ​s​e​r​ ​c​r​i​a​d​o​.
		 */
		RatingGroupLangDesc: string
		/**
		 * I​d​i​o​m​a​s​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingGroupLangTitle: string
		/**
		 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		RatingGroupTitleDesc: string
		/**
		 * T​í​t​u​l​o​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingGroupTitleTitle: string
		/**
		 * P​a​s​s​o​ ​p​a​r​a​ ​c​r​i​a​ç​ã​o​ ​d​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​a​s​s​o​c​i​a​d​a​s​ ​a​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		RatingOptionsDesc: string
		/**
		 * C​r​i​a​r​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingOptionsTitle: string
		/**
		 * A​p​r​e​s​e​n​t​a​r​ ​n​a​ ​l​i​n​g​u​a​g​e​m​:
		 */
		ShowInLanguage: string
		/**
		 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		SingleRatingOptionDesc: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​c​o​m​e​n​t​á​r​i​o
		 */
		SingleRatingOptionNeedComment: string
		/**
		 * T​í​t​u​l​o​ ​d​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		SingleRatingOptionTitle: string
		/**
		 * C​r​i​a​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		Title: string
		/**
		 * E​r​r​o​ ​a​o​ ​c​r​i​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.​ ​T​e​n​t​e​ ​d​e​ ​n​o​v​o
		 */
		ToastError: string
		/**
		 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		ToastSuccess: string
		ValidationError: {
			/**
			 * S​e​l​e​c​i​o​n​e​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​a​ ​l​i​n​g​u​a​g​e​m​ ​p​a​r​a​ ​a​ ​q​u​a​l​ ​s​e​r​á​ ​c​r​i​a​d​o​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​l​a​i​a​ç​ã​o
			 */
			NoLanguages: string
			/**
			 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​d​u​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
			 */
			NoRatingOptions: string
			/**
			 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
			 */
			RatingGroupTitle: string
			/**
			 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​n​a​ ​p​o​s​i​ç​ã​o​ ​{​p​o​s​i​t​i​o​n​}​ ​e​ ​i​d​i​o​m​a​ ​{​l​a​n​g​u​a​g​e​}
			 * @param {unknown} language
			 * @param {unknown} position
			 */
			RatingOptionTitle: RequiredParams<'language' | 'position'>
		}
	}
	EditRatingGroups: {
		/**
		 * A​d​i​c​i​o​n​a​r​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		AddRatingOption: string
		/**
		 * R​e​m​o​v​e​r​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		DeleteRatingOption: string
		/**
		 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​p​o​d​e​ ​r​e​a​l​i​z​a​r​ ​a​ ​e​d​i​ç​ã​o​ ​d​e​ ​u​m​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		Description: string
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​a​d​i​c​i​o​n​a​r​ ​u​m​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​p​o​i​s​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​k​á​ ​e​s​t​á​ ​a​ ​s​e​r​ ​u​s​a​d​o​.
		 */
		IsBeingUsedAdd: string
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​r​e​m​o​v​e​r​ ​u​m​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​p​o​i​s​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​j​á​ ​e​s​t​á​ ​a​ ​s​e​r​ ​u​s​a​d​o​.
		 */
		IsBeingUsedDelete: string
		/**
		 * I​n​s​i​r​a​ ​u​m​a​ ​d​e​s​c​r​i​ç​ã​o​ ​p​a​r​a​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		RatingGroupDescDesc: string
		/**
		 * D​e​s​c​r​i​ç​ã​o​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingGroupDescTitle: string
		/**
		 * S​e​l​e​c​i​o​n​e​ ​o​s​ ​i​d​i​o​m​a​s​ ​p​a​r​a​ ​o​s​ ​q​u​a​i​s​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​v​a​i​ ​s​e​r​ ​c​r​i​a​d​o​.
		 */
		RatingGroupLangDesc: string
		/**
		 * I​d​i​o​m​a​s​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingGroupLangTitle: string
		/**
		 * I​n​s​i​r​a​ ​u​m​ ​t​í​t​u​l​o​ ​p​a​r​a​ ​i​d​e​n​t​i​f​i​c​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.
		 */
		RatingGroupTitleDesc: string
		/**
		 * T​í​t​u​l​o​ ​d​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingGroupTitleTitle: string
		/**
		 * P​a​s​s​o​ ​p​a​r​a​ ​e​d​i​t​a​r​ ​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​a​s​s​o​c​i​a​d​a​s​ ​a​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		RatingOptionsDesc: string
		/**
		 * E​d​i​t​a​r​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingOptionsTitle: string
		/**
		 * A​p​r​e​s​e​n​t​a​r​ ​n​a​ ​l​i​n​g​u​a​g​e​m​:
		 */
		ShowInLanguage: string
		/**
		 * D​e​s​c​r​i​ç​ã​o​ ​d​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		SingleRatingOptionDesc: string
		/**
		 * N​e​c​e​s​s​i​t​a​ ​d​e​ ​c​o​m​e​n​t​á​r​i​o
		 */
		SingleRatingOptionNeedComment: string
		/**
		 * T​í​t​u​l​o​ ​d​a​ ​o​p​ç​ã​o​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		SingleRatingOptionTitle: string
		/**
		 * E​d​i​t​a​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		Title: string
		/**
		 * E​r​r​o​ ​a​o​ ​e​d​i​t​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.​ ​T​e​n​t​e​ ​d​e​ ​n​o​v​o
		 */
		ToastError: string
		/**
		 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​e​d​i​t​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		ToastSuccess: string
	}
	Header: {
		/**
		 * I​n​í​c​i​o
		 */
		Home: string
	}
	HomeBackoffice: {
		/**
		 * A​v​a​l​i​a​ç​õ​e​s​ ​A​t​i​v​a​s
		 */
		ActiveReviews: string
		/**
		 * A​v​a​l​i​a​ç​õ​e​s​ ​C​o​m​p​l​e​t​a​s
		 */
		CompletedReviews: string
		/**
		 * A​v​a​l​i​a​ç​õ​e​s
		 */
		Reviews: string
		/**
		 * M​o​d​e​l​o​s
		 */
		Templates: string
	}
	Languages: {
		/**
		 * I​n​g​l​ê​s
		 */
		EN: string
		/**
		 * E​s​p​a​n​h​o​l
		 */
		ES: string
		/**
		 * F​r​a​n​c​ê​s
		 */
		FR: string
		/**
		 * P​o​l​a​c​o
		 */
		PL: string
		/**
		 * P​o​r​t​u​g​u​ê​s
		 */
		PT: string
	}
	Menu: {
		/**
		 * C​a​t​e​g​o​r​i​a​s
		 */
		Categories: string
		/**
		 * I​n​í​c​i​o
		 */
		Home: string
		/**
		 * D​e​s​e​m​p​e​n​h​o
		 */
		Performance: string
		/**
		 * P​e​r​m​i​s​s​õ​e​s
		 */
		Permissions: string
		/**
		 * C​r​i​t​é​r​i​o​s​ ​d​e​ ​A​v​a​l​i​a​ç​ã​o
		 */
		RatingGroups: string
		/**
		 * A​v​a​l​i​a​ç​õ​e​s
		 */
		Reviews: string
		/**
		 * E​s​t​a​t​í​s​t​i​c​a​s
		 */
		Statistics: string
		/**
		 * S​u​b​m​i​s​s​õ​e​s
		 */
		Submissions: string
		/**
		 * D​e​s​e​m​p​e​n​h​o​ ​E​q​u​i​p​a
		 */
		TeamPerformance: string
		/**
		 * M​o​d​e​l​o​s
		 */
		Templates: string
	}
	Permissions: {
		/**
		 * S​e​l​e​c​i​o​n​a​r​ ​p​e​r​f​i​l
		 */
		ChooseProfile: string
		/**
		 * S​e​l​e​c​i​o​n​e​ ​o​ ​p​e​r​f​i​l​ ​a​o​ ​q​u​a​l​ ​d​e​s​e​j​a​ ​a​l​t​e​r​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s
		 */
		ChooseProfileDesc: string
		/**
		 * A​ ​c​a​r​r​e​g​a​r
		 */
		Loading: string
		PermissionType: {
			/**
			 * C​r​i​a​r
			 */
			Create: string
			/**
			 * R​e​m​o​v​e​r
			 */
			Delete: string
			/**
			 * A​l​t​e​r​a​r​ ​e​s​t​a​d​o
			 */
			Patch: string
			/**
			 * A​c​e​s​s​a​r
			 */
			Read: string
			/**
			 * E​d​i​t​a​r
			 */
			Update: string
		}
		/**
		 * P​e​r​m​i​s​s​õ​e​s​ ​d​o​ ​p​e​r​f​i​l​ ​g​u​a​r​d​a​d​a​s​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		PermissionsSave: string
		/**
		 * O​c​o​r​r​e​u​ ​u​m​ ​e​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​g​r​a​v​a​r​ ​a​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​d​o​ ​p​e​r​f​i​l
		 */
		PermissionsSaveError: string
		/**
		 * G​u​a​r​d​a​r
		 */
		Save: string
	}
	RatingGroups: {
		/**
		 * C​r​i​a​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		CreateButton: string
		/**
		 * N​e​s​t​a​ ​p​á​g​i​n​a​ ​s​ã​o​ ​l​i​s​t​a​d​o​s​ ​t​o​d​o​s​ ​o​s​ ​g​r​u​p​o​s​ ​d​e​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​c​r​i​a​d​o​s​ ​e​ ​a​r​m​a​z​e​n​a​d​o​s​ ​e​m​ ​b​a​s​e​ ​d​e​ ​d​a​d​o​s​.​ ​E​s​t​e​s​ ​g​r​u​p​o​s​ ​d​e​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​s​e​r​v​e​m​ ​p​a​r​a​ ​o​ ​u​t​i​l​i​z​a​d​o​r​ ​r​e​s​p​o​n​d​e​r​ ​à​s​ ​p​e​r​g​u​n​t​a​s​ ​c​o​m​ ​t​i​p​o​ ​C​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​d​a​s​ ​a​v​a​l​i​a​ç​õ​e​s​.​ ​P​o​d​e​ ​a​s​s​o​c​i​a​r​ ​u​m​ ​i​t​e​m​ ​d​e​s​t​a​ ​p​á​g​i​n​a​ ​c​o​m​ ​u​m​a​ ​s​u​b​-​a​v​a​l​i​a​ç​ã​o​,​ ​o​n​d​e​ ​d​e​s​e​j​a​ ​u​t​i​l​i​z​a​r​ ​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​c​r​i​a​d​o​.
		 */
		Description: string
		/**
		 * E​r​r​o​ ​a​o​ ​t​e​n​t​a​r​ ​l​i​s​t​a​r​ ​o​s​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		Error: string
		/**
		 * F​i​l​t​r​a​r​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​p​e​l​o​ ​t​í​t​u​l​o​.​.​.
		 */
		InputText: string
		/**
		 * A​ ​c​a​r​r​e​g​a​r​.​.​.
		 */
		Loading: string
		/**
		 * N​ã​o​ ​e​x​i​s​t​e​m​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​d​i​s​p​o​n​í​v​e​i​s​ ​d​e​ ​m​o​m​e​n​t​o​.​ ​V​o​l​t​e​ ​m​a​i​s​ ​t​a​r​d​e​ ​o​u​ ​c​r​i​e​ ​u​m​ ​n​o​v​o​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​p​a​r​a​ ​c​o​m​e​ç​a​r​!
		 */
		NoRatingGroups: string
		/**
		 * N​ã​o​ ​f​o​r​a​m​ ​e​n​c​o​n​t​r​a​d​o​s​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​q​u​e​ ​c​o​r​r​e​s​p​o​n​d​a​m​ ​à​ ​s​u​a​ ​p​e​s​q​u​i​s​a​.​ ​T​e​n​t​e​ ​a​j​u​s​t​a​r​ ​a​s​ ​p​a​l​a​v​r​a​s​-​c​h​a​v​e​ ​o​u​ ​l​i​m​p​e​ ​o​ ​f​i​l​t​r​o​ ​p​a​r​a​ ​v​e​r​ ​t​o​d​o​s​ ​o​s​ ​c​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​d​i​s​p​o​n​í​v​e​i​s​.
		 */
		NoRatingGroupsFilter: string
		/**
		 * P​r​é​-​V​i​s​u​a​l​i​z​a​r
		 */
		Preview: string
		/**
		 * E​x​i​b​i​n​d​o​ ​{​f​i​r​s​t​E​l​e​m​e​n​t​}​ ​a​t​é​ ​{​p​a​g​e​S​i​z​e​}​ ​d​e​ ​{​t​o​t​a​l​}​ ​i​t​e​m​s
		 * @param {unknown} firstElement
		 * @param {unknown} pageSize
		 * @param {unknown} total
		 */
		ShowingItemsLabel: RequiredParams<'firstElement' | 'pageSize' | 'total'>
		/**
		 * C​r​i​t​é​r​i​o​s​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o
		 */
		Title: string
		/**
		 * C​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​r​e​m​o​v​i​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
		 */
		ToastDelete: string
		/**
		 * E​r​r​o​ ​a​o​ ​r​e​m​o​v​e​r​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​.​ ​T​e​n​t​e​ ​d​e​ ​n​o​v​o​.
		 */
		ToastDeleteError: string
	}
	Sidebar: {
		/**
		 * M​e​n​u​ ​B​a​c​k​o​f​f​i​c​e
		 */
		Backoffice: string
		/**
		 * M​e​n​u​ ​F​r​o​n​t​o​f​f​i​c​e
		 */
		Frontoffice: string
		/**
		 * O​l​á
		 */
		Hello: string
		/**
		 * U​t​i​l​i​z​a​d​o​r
		 */
		User: string
	}
	SingleRatingGroups: {
		/**
		 * C​r​i​a​d​o​ ​p​o​r​ ​u​t​i​l​i​z​a​d​o​r
		 */
		CreateBy: string
		/**
		 * D​a​t​a​ ​d​e​ ​c​r​i​a​ç​ã​o
		 */
		CreateDate: string
		/**
		 * D​e​s​c​r​i​ç​ã​o
		 */
		Description: string
		/**
		 * *​ ​r​e​s​p​o​n​d​e​r​ ​à​ ​q​u​e​s​t​ã​o​ ​c​o​m​ ​e​s​t​a​ ​o​p​ç​ã​o​ ​o​b​r​i​g​a​ ​o​ ​u​t​i​l​i​z​a​d​o​r​ ​a​ ​a​d​i​c​i​o​n​a​r​ ​u​m​ ​c​o​m​e​n​t​á​r​i​o​ ​à​ ​r​e​s​p​o​s​t​a
		 */
		NeedComment: string
		/**
		 * O​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingOptions: string
		/**
		 * A​b​a​i​x​o​ ​e​s​t​ã​o​ ​l​i​s​t​a​d​a​s​ ​a​s​ ​o​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o​ ​p​a​r​a​ ​r​e​s​p​o​s​t​a​ ​à​s​ ​q​u​e​s​t​õ​e​s​ ​d​e​ ​u​m​a​ ​a​v​a​l​i​a​ç​ã​o​/​s​u​b​-​a​v​a​l​i​a​ç​ã​o​ ​a​o​ ​q​u​a​l​ ​e​s​t​e​ ​c​r​i​t​é​r​i​o​ ​d​e​ ​a​v​a​l​i​a​ç​ã​o​ ​e​s​t​á​ ​a​s​s​o​c​i​a​d​o​.​ ​C​l​i​q​u​e​ ​n​o​ ​e​l​e​m​e​n​t​o​ ​d​e​ ​s​e​l​e​ç​ã​o​ ​p​a​r​a​ ​a​l​t​e​r​n​a​r​ ​e​n​t​r​e​ ​o​s​ ​i​d​i​o​m​a​s​ ​d​i​s​p​o​n​í​v​e​i​s​.
		 */
		RatingOptionsDesc: string
	}
	Steps: {
		/**
		 * D​e​t​a​l​h​e​s
		 */
		Details: string
		/**
		 * F​i​n​a​l​i​z​a​r
		 */
		Finalize: string
		/**
		 * A​v​a​n​ç​a​r
		 */
		Forward: string
		/**
		 * O​p​ç​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingOptions: string
		/**
		 * Q​u​e​s​t​õ​e​s​ ​d​e​ ​c​l​a​s​s​i​f​i​c​a​ç​ã​o
		 */
		RatingQuestions: string
		/**
		 * V​o​l​t​a​r
		 */
		Return: string
		/**
		 * Q​u​e​s​t​õ​e​s​ ​d​e​ ​t​e​x​t​o
		 */
		TextQuestions: string
	}
}

export type TranslationFunctions = {
	App: {
		/**
		 * A carregar
		 */
		Loading: () => LocalizedString
		/**
		 * Sem Login
		 */
		NoLogin: () => LocalizedString
		/**
		 * O utilizador necessita de fazer o login antes de acessar a página.
		 */
		NoLoginDesc: () => LocalizedString
		/**
		 * Utilizador não tem tipo de perfil
		 */
		NoUserProfileType: () => LocalizedString
		/**
		 * O utilizador não tem nenhum tipo de perfil associado seja frontoffice ou backoffice. Tente solucionar este problema antes de acessar a página.
		 */
		NoUserProfileTypeDesc: () => LocalizedString
	}
	Categories: {
		/**
		 * Criar categoria
		 */
		CreateButton: () => LocalizedString
		/**
		 * Nesta página são listadas todas as categorias, e as suas respetivas questões, criadas e armazenadas em base de dados. Estas categorias são utilizadas na criação da avaliação/sub-avaliações para criar um formulário ao qual os utilizadores irão responder. Ao criar a avaliação puderá associar a esta as categorias e respetivas questões que desejar.
		 */
		Description: () => LocalizedString
		/**
		 * Erro ao tentar listar as categorias
		 */
		Error: () => LocalizedString
		/**
		 * Filtar categorias pelo título...
		 */
		InputText: () => LocalizedString
		/**
		 * A carregar...
		 */
		Loading: () => LocalizedString
		/**
		 * Não existem categorias disponíveis de momento. Volte mais tarde ou crie uma nova categoria para começar!
		 */
		NoCategories: () => LocalizedString
		/**
		 * Não foram encotradas categorias que correspondam à sua pesquisa. Tente ajustar as palavras-chave ou limpe o filtro para ver todas as categorias disponíveis.
		 */
		NoCategoriesFilter: () => LocalizedString
		/**
		 * Pré-Visualizar
		 */
		Preview: () => LocalizedString
		/**
		 * Exibindo {firstElement} até {pageSize} de {total} items
		 */
		ShowingItemsLabel: (arg: { firstElement: unknown, pageSize: unknown, total: unknown }) => LocalizedString
		/**
		 * Categorias e Questões
		 */
		Title: () => LocalizedString
		/**
		 * Categoria removida com sucesso.
		 */
		ToastDelete: () => LocalizedString
		/**
		 * Erro ao remover categoria. Tente de novo.
		 */
		ToastDeleteError: () => LocalizedString
	}
	CreateCategory: {
		/**
		 * Adicionar questão
		 */
		AddQuestion: () => LocalizedString
		/**
		 * Insira uma descrição para a categoria
		 */
		CategoryDescDesc: () => LocalizedString
		/**
		 * Descrição da categoria
		 */
		CategoryDescTitle: () => LocalizedString
		/**
		 * Insira um título para identificar a categoria.
		 */
		CategoryTitleDesc: () => LocalizedString
		/**
		 * Título da categoria
		 */
		CategoryTitleTitle: () => LocalizedString
		/**
		 * Continuar
		 */
		Continue: () => LocalizedString
		/**
		 * Remover questão
		 */
		DeleteQuestion: () => LocalizedString
		/**
		 * Nesta página pode realizar a criação de uma nova categoria juntamente com as suas questões. Esta categoria pode ser posteriormente associada a uma avaliação para que o utilizador ao responder à avaliação, responda ás questões da categoria.
		 */
		Description: () => LocalizedString
		/**
		 * Selecione para quais idiomas deseja criar a categoria.
		 */
		LanguageDesc: () => LocalizedString
		/**
		 * Selecione o(s) idioma(s)
		 */
		LanguageTitle: () => LocalizedString
		/**
		 * (Sem título)
		 */
		NoTitle: () => LocalizedString
		/**
		 * Descrição da questão
		 */
		QuestionDesc: () => LocalizedString
		/**
		 * Título da questão
		 */
		QuestionTitle: () => LocalizedString
		/**
		 * Passo para criação de questões de classificação associadas à categoria
		 */
		RatingQuestionsDesc: () => LocalizedString
		/**
		 * Criar questões de classificação
		 */
		RatingQuestionsTitle: () => LocalizedString
		/**
		 * Apresentar na linguagem:
		 */
		ShowInLanguage: () => LocalizedString
		/**
		 * Passo para criação de questões de texto associadas à categoria
		 */
		TextQuestionsDesc: () => LocalizedString
		/**
		 * Criar questões de texto
		 */
		TextQuestionsTitle: () => LocalizedString
		/**
		 * Criar categoria e questões
		 */
		Title: () => LocalizedString
		/**
		 * Erro ao criar categoria. Tente de novo
		 */
		ToastError: () => LocalizedString
		/**
		 * Categoria criada com sucesso
		 */
		ToastSuccess: () => LocalizedString
		ValidationError: {
			/**
			 * Insira um título para a categoria em {language}
			 */
			CategoryTitle: (arg: { language: unknown }) => LocalizedString
			/**
			 * Selecione pelo menos uma linguagem para a qual será criada a categoria
			 */
			NoLanguages: () => LocalizedString
			/**
			 * Categoria deve ter pelo menos uma questão
			 */
			NoQuestions: () => LocalizedString
			/**
			 * Questões devem ter um título em todas as linguagens
			 */
			QuestionTitle: () => LocalizedString
		}
	}
	CreateRatingGroups: {
		/**
		 * Adicionar opção de classificação
		 */
		AddRatingOption: () => LocalizedString
		/**
		 * Remover opção de classificação
		 */
		DeleteRatingOption: () => LocalizedString
		/**
		 * Nesta página pode realizar a criação de critérios de avaliação. Cada critério de avaliação é criado com um grupo de opções de classificação que é usado como resposta a questões do tipo Classificação quando associado a uma avaliação/sub-avaliação.
		 */
		Description: () => LocalizedString
		/**
		 * Insira uma descrição para o critério de avaliação.
		 */
		RatingGroupDescDesc: () => LocalizedString
		/**
		 * Descrição do critério de avaliação
		 */
		RatingGroupDescTitle: () => LocalizedString
		/**
		 * Selecione os idiomas para os quais este critério de avaliação vai ser criado.
		 */
		RatingGroupLangDesc: () => LocalizedString
		/**
		 * Idiomas do critério de avaliação
		 */
		RatingGroupLangTitle: () => LocalizedString
		/**
		 * Insira um título para identificar o critério de avaliação.
		 */
		RatingGroupTitleDesc: () => LocalizedString
		/**
		 * Título do critério de avaliação
		 */
		RatingGroupTitleTitle: () => LocalizedString
		/**
		 * Passo para criação das opções de classificação associadas ao critério de avaliação.
		 */
		RatingOptionsDesc: () => LocalizedString
		/**
		 * Criar opções de classificação
		 */
		RatingOptionsTitle: () => LocalizedString
		/**
		 * Apresentar na linguagem:
		 */
		ShowInLanguage: () => LocalizedString
		/**
		 * Descrição da opção de classificação
		 */
		SingleRatingOptionDesc: () => LocalizedString
		/**
		 * Necessita de comentário
		 */
		SingleRatingOptionNeedComment: () => LocalizedString
		/**
		 * Título da opção de classificação
		 */
		SingleRatingOptionTitle: () => LocalizedString
		/**
		 * Criar critério de avaliação
		 */
		Title: () => LocalizedString
		/**
		 * Erro ao criar o critério de avaliação. Tente de novo
		 */
		ToastError: () => LocalizedString
		/**
		 * Critério de avaliação criado com sucesso
		 */
		ToastSuccess: () => LocalizedString
		ValidationError: {
			/**
			 * Selecione pelo menos uma linguagem para a qual será criado o critério de avlaiação
			 */
			NoLanguages: () => LocalizedString
			/**
			 * Critério de avaliação deve ter pelo menos duas opções de classificação
			 */
			NoRatingOptions: () => LocalizedString
			/**
			 * Insira um título para o critério de avaliação
			 */
			RatingGroupTitle: () => LocalizedString
			/**
			 * Insira um título para a opção de classificação na posição {position} e idioma {language}
			 */
			RatingOptionTitle: (arg: { language: unknown, position: unknown }) => LocalizedString
		}
	}
	EditRatingGroups: {
		/**
		 * Adicionar opção de classificação
		 */
		AddRatingOption: () => LocalizedString
		/**
		 * Remover opção de classificação
		 */
		DeleteRatingOption: () => LocalizedString
		/**
		 * Nesta página pode realizar a edição de um critério de avaliação.
		 */
		Description: () => LocalizedString
		/**
		 * Não é possível adicionar uma opção de classificação pois este critério de avaliação ká está a ser usado.
		 */
		IsBeingUsedAdd: () => LocalizedString
		/**
		 * Não é possível remover uma opção de classificação pois este critério de avaliação já está a ser usado.
		 */
		IsBeingUsedDelete: () => LocalizedString
		/**
		 * Insira uma descrição para o critério de avaliação.
		 */
		RatingGroupDescDesc: () => LocalizedString
		/**
		 * Descrição do critério de avaliação
		 */
		RatingGroupDescTitle: () => LocalizedString
		/**
		 * Selecione os idiomas para os quais este critério de avaliação vai ser criado.
		 */
		RatingGroupLangDesc: () => LocalizedString
		/**
		 * Idiomas do critério de avaliação
		 */
		RatingGroupLangTitle: () => LocalizedString
		/**
		 * Insira um título para identificar o critério de avaliação.
		 */
		RatingGroupTitleDesc: () => LocalizedString
		/**
		 * Título do critério de avaliação
		 */
		RatingGroupTitleTitle: () => LocalizedString
		/**
		 * Passo para editar as opções de classificação associadas ao critério de avaliação
		 */
		RatingOptionsDesc: () => LocalizedString
		/**
		 * Editar opções de classificação
		 */
		RatingOptionsTitle: () => LocalizedString
		/**
		 * Apresentar na linguagem:
		 */
		ShowInLanguage: () => LocalizedString
		/**
		 * Descrição da opção de classificação
		 */
		SingleRatingOptionDesc: () => LocalizedString
		/**
		 * Necessita de comentário
		 */
		SingleRatingOptionNeedComment: () => LocalizedString
		/**
		 * Título da opção de classificação
		 */
		SingleRatingOptionTitle: () => LocalizedString
		/**
		 * Editar critério de avaliação
		 */
		Title: () => LocalizedString
		/**
		 * Erro ao editar o critério de avaliação. Tente de novo
		 */
		ToastError: () => LocalizedString
		/**
		 * Critério de avaliação editado com sucesso
		 */
		ToastSuccess: () => LocalizedString
	}
	Header: {
		/**
		 * Início
		 */
		Home: () => LocalizedString
	}
	HomeBackoffice: {
		/**
		 * Avaliações Ativas
		 */
		ActiveReviews: () => LocalizedString
		/**
		 * Avaliações Completas
		 */
		CompletedReviews: () => LocalizedString
		/**
		 * Avaliações
		 */
		Reviews: () => LocalizedString
		/**
		 * Modelos
		 */
		Templates: () => LocalizedString
	}
	Languages: {
		/**
		 * Inglês
		 */
		EN: () => LocalizedString
		/**
		 * Espanhol
		 */
		ES: () => LocalizedString
		/**
		 * Francês
		 */
		FR: () => LocalizedString
		/**
		 * Polaco
		 */
		PL: () => LocalizedString
		/**
		 * Português
		 */
		PT: () => LocalizedString
	}
	Menu: {
		/**
		 * Categorias
		 */
		Categories: () => LocalizedString
		/**
		 * Início
		 */
		Home: () => LocalizedString
		/**
		 * Desempenho
		 */
		Performance: () => LocalizedString
		/**
		 * Permissões
		 */
		Permissions: () => LocalizedString
		/**
		 * Critérios de Avaliação
		 */
		RatingGroups: () => LocalizedString
		/**
		 * Avaliações
		 */
		Reviews: () => LocalizedString
		/**
		 * Estatísticas
		 */
		Statistics: () => LocalizedString
		/**
		 * Submissões
		 */
		Submissions: () => LocalizedString
		/**
		 * Desempenho Equipa
		 */
		TeamPerformance: () => LocalizedString
		/**
		 * Modelos
		 */
		Templates: () => LocalizedString
	}
	Permissions: {
		/**
		 * Selecionar perfil
		 */
		ChooseProfile: () => LocalizedString
		/**
		 * Selecione o perfil ao qual deseja alterar as permissões
		 */
		ChooseProfileDesc: () => LocalizedString
		/**
		 * A carregar
		 */
		Loading: () => LocalizedString
		PermissionType: {
			/**
			 * Criar
			 */
			Create: () => LocalizedString
			/**
			 * Remover
			 */
			Delete: () => LocalizedString
			/**
			 * Alterar estado
			 */
			Patch: () => LocalizedString
			/**
			 * Acessar
			 */
			Read: () => LocalizedString
			/**
			 * Editar
			 */
			Update: () => LocalizedString
		}
		/**
		 * Permissões do perfil guardadas com sucesso
		 */
		PermissionsSave: () => LocalizedString
		/**
		 * Ocorreu um erro ao tentar gravar as permissões do perfil
		 */
		PermissionsSaveError: () => LocalizedString
		/**
		 * Guardar
		 */
		Save: () => LocalizedString
	}
	RatingGroups: {
		/**
		 * Criar critério de avaliação
		 */
		CreateButton: () => LocalizedString
		/**
		 * Nesta página são listados todos os grupos de opções de classificação criados e armazenados em base de dados. Estes grupos de opções de classificação servem para o utilizador responder às perguntas com tipo Classificação das avaliações. Pode associar um item desta página com uma sub-avaliação, onde deseja utilizar o critério de avaliação criado.
		 */
		Description: () => LocalizedString
		/**
		 * Erro ao tentar listar os critérios de avaliação
		 */
		Error: () => LocalizedString
		/**
		 * Filtrar critérios de avaliação pelo título...
		 */
		InputText: () => LocalizedString
		/**
		 * A carregar...
		 */
		Loading: () => LocalizedString
		/**
		 * Não existem critérios de avaliação disponíveis de momento. Volte mais tarde ou crie um novo critério de avaliação para começar!
		 */
		NoRatingGroups: () => LocalizedString
		/**
		 * Não foram encontrados critérios de avaliação que correspondam à sua pesquisa. Tente ajustar as palavras-chave ou limpe o filtro para ver todos os critérios de avaliação disponíveis.
		 */
		NoRatingGroupsFilter: () => LocalizedString
		/**
		 * Pré-Visualizar
		 */
		Preview: () => LocalizedString
		/**
		 * Exibindo {firstElement} até {pageSize} de {total} items
		 */
		ShowingItemsLabel: (arg: { firstElement: unknown, pageSize: unknown, total: unknown }) => LocalizedString
		/**
		 * Critérios de avaliação
		 */
		Title: () => LocalizedString
		/**
		 * Critério de avaliação removido com sucesso.
		 */
		ToastDelete: () => LocalizedString
		/**
		 * Erro ao remover critério de avaliação. Tente de novo.
		 */
		ToastDeleteError: () => LocalizedString
	}
	Sidebar: {
		/**
		 * Menu Backoffice
		 */
		Backoffice: () => LocalizedString
		/**
		 * Menu Frontoffice
		 */
		Frontoffice: () => LocalizedString
		/**
		 * Olá
		 */
		Hello: () => LocalizedString
		/**
		 * Utilizador
		 */
		User: () => LocalizedString
	}
	SingleRatingGroups: {
		/**
		 * Criado por utilizador
		 */
		CreateBy: () => LocalizedString
		/**
		 * Data de criação
		 */
		CreateDate: () => LocalizedString
		/**
		 * Descrição
		 */
		Description: () => LocalizedString
		/**
		 * * responder à questão com esta opção obriga o utilizador a adicionar um comentário à resposta
		 */
		NeedComment: () => LocalizedString
		/**
		 * Opções de classificação
		 */
		RatingOptions: () => LocalizedString
		/**
		 * Abaixo estão listadas as opções de classificação para resposta às questões de uma avaliação/sub-avaliação ao qual este critério de avaliação está associado. Clique no elemento de seleção para alternar entre os idiomas disponíveis.
		 */
		RatingOptionsDesc: () => LocalizedString
	}
	Steps: {
		/**
		 * Detalhes
		 */
		Details: () => LocalizedString
		/**
		 * Finalizar
		 */
		Finalize: () => LocalizedString
		/**
		 * Avançar
		 */
		Forward: () => LocalizedString
		/**
		 * Opções de classificação
		 */
		RatingOptions: () => LocalizedString
		/**
		 * Questões de classificação
		 */
		RatingQuestions: () => LocalizedString
		/**
		 * Voltar
		 */
		Return: () => LocalizedString
		/**
		 * Questões de texto
		 */
		TextQuestions: () => LocalizedString
	}
}

export type Formatters = {}
